/*
 tempura - simple templating library in javascript.
 https://github.com/nakamura-to/tempura
*/
(function(n){var g={toString:Object.prototype.toString,slice:Array.prototype.slice,isObject:function(a){return a===Object(a)},isPlainObject:function(a){return"[object Object]"===g.toString.call(a)},isArray:function(a){return"[object Array]"===g.toString.call(a)},isFunction:function(a){return"[object Function]"===g.toString.call(a)},isString:function(a){return"[object String]"===g.toString.call(a)},trim:function(a){return null===a||void 0===a?"":a.replace(/^\s+/,"").replace(/\s+$/,"")},extend:function(a){var d=
g.slice.call(arguments,1),b=d.length,e,c,f;if(null===a||void 0===a||0===b)return a;for(e=0;e<b;e++)if(c=d[e],null!==c&&void 0!==c)for(f in c)void 0===a[f]&&(a[f]=c[f]);return a},deepExtend:function(a){var d=g.slice.call(arguments,1),b=d.length,e,c,f;if(null===a||void 0===a||0===b)return a;f=function(a,b){var d,e,c;for(d in b){e=b[d];c=a[d];var i=g.isArray(e);i||g.isPlainObject(e)?(c=c||(i?[]:{}),f(c,e),a[d]=c):void 0===c&&(a[d]=e)}};for(e=0;e<b;e++)c=d[e],null!==c&&void 0!==c&&f(a,c);return a},encode:function(a){return(null===
a||void 0===a?"":""+a).replace(/[&"'<>]/g,function(a){switch(a){case "&":return"&amp;";case '"':return"&quot;";case "'":return"&#39;";case "<":return"&lt;";case ">":return"&gt;";default:return a}})}},c={TEMPURA_CONTEXT_MARK:"__tempura__",TEMPURA_OPTIONS:"__tempura__options",ROOT_CONTEXT:"$root",PARENT_CONTEXT:"$parent",THIS:"$this",includes:function(a,c){return-1!==c.indexOf("{{"+a)},createContext:function(a,d){var b;if(d[c.TEMPURA_CONTEXT_MARK])return d;if(!a[c.TEMPURA_CONTEXT_MARK])throw Error("illegal parent context.");
b={};b[c.TEMPURA_CONTEXT_MARK]=!0;b[c.TEMPURA_OPTIONS]=a[c.TEMPURA_OPTIONS];b[c.ROOT_CONTEXT]=a[c.ROOT_CONTEXT];b[c.PARENT_CONTEXT]=a;b[c.THIS]=d;return g.extend(b,d)},walk:function(a,d){for(var b=a.split("."),e=d[b.shift()];null!==e&&void 0!==e&&0<b.length;)d=c.createContext(d,e),e=d[b.shift()];return{found:void 0!==e&&0===b.length,value:e,context:d}},applyPipes:function(a,d,b){var e=b[c.TEMPURA_OPTIONS]||{},i=e.pipes||{},e=e.noSuchPipe,f,j,h,l=d.length,k;for(h=0;h<l;h++)k=d[h],f=c.walk(k,b),j=f.value,
g.isFunction(j)?a=j.call(f.context,a):(f=i[k],g.isFunction(f)?a=f.call(b,a):g.isFunction(e)&&(a=e.call(b,k,h,a)));return a},applyPreRender:function(a,d,b){var e=(d[c.TEMPURA_OPTIONS]||{}).preRender;return g.isFunction(e)?e.call(d,a,b):b(a)},noSuchValue:function(a,d){var b=(d[c.TEMPURA_OPTIONS]||{}).noSuchValue;return g.isFunction(b)?b.call(d,a):void 0},resolveValue:function(a,d,b){var e=c.walk(a,b),a=e.found?e.value:c.noSuchValue(a,b);g.isFunction(a)&&(a=a.call(e.context));return c.applyPreRender(a,
b,function(a){return c.applyPipes(a,d,b)})},transformTags:function(){var a=RegExp("{{([#\\^/!{])?(.+?)(?:\\|(.*?))?}}+","g"),d=function(a,e,d){var a=g.trim(a),f,j,h,l=[];if(null!==e&&void 0!==e){e=e.split("|");j=e.length;for(f=0;f<j;f++)(h=g.trim(e[f]))&&l.push(h)}d=c.resolveValue(a,l,d);return null===d||void 0===d?"":""+d};return function(b,c){var i=function(a,b,f,h){switch(b){case "#":return"{{#"+f+"}}";case "^":return"{{^"+f+"}}";case "/":return"{{/"+f+"}}";case "!":return"";case "{":return d(f,
h,c);default:return g.encode(d(f,h,c))}},f=b.split("\n"),j,h,l=f.length;for(h=0;h<l;h++)j=f[h],f[h]=j.replace(a,i);return f.join("\n")}}(),transformSection:function(){var a=RegExp("^([\\s\\S]*?){{([#\\^])\\s*(.+)\\s*}}\n*([\\s\\S]*?){{\\/\\s*\\3\\s*}}\n*([\\s\\S]*)$","g"),d=function(a,d,i,f){var j=i.length,h=[];if("#"===a){if(g.isArray(i)){for(a=0;a<j;a++)h[a]=c.transform(d,c.createContext(f,i[a]));return h.join("")}if(g.isFunction(i)){if(i.call(f))return c.transform(d,f)}else{if(g.isObject(i))return c.transform(d,
c.createContext(f,i));if(i)return c.transform(d,f)}}else if("^"===a&&(g.isArray(i)&&0===i.length||!i))return c.transform(d,f);return""};return function(b,e){return!c.includes("#",b)&&!c.includes("^",b)?!1:b.replace(a,function(a,b,g,h,l,k){a=b?c.transformTags(b,e):"";k=k?c.transform(k,e):"";b=c.walk(h,e);h=b.found?b.value:c.noSuchValue(h,e);g=d(g,l,h,b.context);return a+g+k})}}(),transform:function(a,d){var b=c.transformSection(a,d);!1===b&&(b=c.transformTags(a,d));return b},createInitialContext:function(a,
d){var b={};b[c.TEMPURA_CONTEXT_MARK]=!0;b[c.TEMPURA_OPTIONS]=d;b[c.ROOT_CONTEXT]=b;b[c.PARENT_CONTEXT]=null;b[c.THIS]=a;g.extend(b,a);return b},toHtml:function(a,d,b){d=c.createInitialContext(d,b);return c.transform(a,d)},prepare:function(a,d){return{render:function(b){return c.toHtml(a,b,d)}}}},m=function(){var a=g.deepExtend({},{pipes:{},preRender:function(a,b){var c=b(a);return void 0===c?"":c},noSuchValue:function(){},noSuchPipe:function(a,b,c){return c}});return{name:"tempura",version:"0.0.1",
getSettings:function(){return a},setSettings:function(c){a=c},mergeSettings:function(c){a=g.deepExtend({},c,a)},prepare:function(d,b){b=g.deepExtend({},b,a);return c.prepare(d,b)},internal:{util:g,core:c}}}();"undefined"!==typeof module?module.exports=m:n.tempura=m})(this);
